const dataChank = {
  data: [
    {
      chatImage: 'assets/images/avatar-2.jpg',
      imageAlt: 'woman with black lips.',
      chatName: 'Андрей',
      lastMessage: '72 метра любви.',
      messageTime: '10:49',
      isNewMessage: 'true',
      isMyLast: 'false',
    },
    {
      chatImage: 'assets/images/avatar-1.jpg',
      imageAlt: 'friendliest old man.',
      chatName: 'Киноклуб',
      lastMessage: 'Привет!',
      messageTime: '11:30',
      isNewMessage: 'false',
      isMyLast: 'true',
    },
    {
      chatImage: 'assets/images/avatar-3.jpg',
      imageAlt: 'man with black cap and glasses.',
      chatName: 'Sasha',
      lastMessage: 'Друзья, у меня для вас особенный выпуск новостей!...',
      messageTime: '10:20',
      isNewMessage: 'true',
      isMyLast: 'false',
    },
    {
      chatImage: 'assets/images/avatar-4.jpg',
      imageAlt: 'man with smile and glasses.',
      chatName: 'Друг',
      lastMessage:
        'И Human Interface Guidelines и Material Design рекомендуют...',
      messageTime: 'Пн',
      isNewMessage: 'false',
      isMyLast: 'true',
    },
    {
      chatImage: 'assets/images/avatar-5.jpg',
      imageAlt: '3d woman with doll emotions.',
      chatName: 'Брат',
      lastMessage: 'Займи плиз<3',
      messageTime: 'Пт',
      isNewMessage: 'true',
      isMyLast: 'false',
    },
    {
      chatImage: 'assets/images/avatar-4.jpg',
      imageAlt: 'man with smile and glasses.',
      chatName: 'Сват',
      lastMessage: 'Привет!',
      messageTime: 'Сб',
      isNewMessage: 'false',
      isMyLast: 'true',
    },
    {
      chatImage: 'assets/images/avatar-3.jpg',
      imageAlt: 'man with black cap and glasses.',
      chatName: 'Ксюша',
      lastMessage: 'Миллионы россиян ежедневно проводят десятки часов свое...',
      messageTime: 'Сб',
      isNewMessage: 'true',
      isMyLast: 'false',
    },
    {
      chatImage: 'assets/images/avatar-1.jpg',
      imageAlt: 'friendliest old man.',
      chatName: 'Химчистка',
      lastMessage:
        'Так увлёкся работой по курсу, что совсем забыл его анонсир...',
      messageTime: 'Вс',
      isNewMessage: 'false',
      isMyLast: 'true',
    },
    {
      chatImage: 'assets/images/avatar-2.jpg',
      imageAlt: 'woman with black lips.',
      chatName: 'Потолки',
      lastMessage: 'Можно или сегодня или завтра вечером.',
      messageTime: '1 Мая 2020',
      isNewMessage: 'true',
      isMyLast: 'false',
    },
    {
      chatImage: 'assets/images/avatar-5.jpg',
      imageAlt: '3d woman with doll emotions.',
      chatName: 'Кот',
      lastMessage: 'Привет!',
      messageTime: '12 Апр 2020',
      isNewMessage: 'false',
      isMyLast: 'true',
    },
  ],
};

// export const chatsContext = {
//   messageField: true,
//   ...dataChank,
// };
